# site properties and page defaults
title: UCF DRACO LAB
subtitle: Design of Resilient Architectures for Computing
description: Coming Fall 2023
header: images/background.jpg
footer: images/background.jpg
website: http://ece.ucf.edu/
basewebsite: /DRACO

# site social media and other links
links:
  email: mike.borowczak@ucf.edu
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: ucf-draco-lab
  gitlab: ucfdracolab
  twitter: 
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_news
  - scope:
      type: "news"
    values:
      layout: post
  - scope:
      type: "projects"
    values:
      layout: project
collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  news:
    output: true
  projects:
    output: true
    
# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
