- title: On the Development of Cybersecurity and Computing Centric Professional Developments
    and the Subsequent Implementation of Topics in K12 Lesson Plans (RTP)
  authors:
  - Andey Robins
  - Andrea C Burrows
  - Mike Borowczak
- title: The Artful Craft of Improving Virtual Summer Camps in the Midst of COVID-19
    (Work in Progress)
  authors:
  - Shawna Wolf
  - Shaya Wolf
  - Hui Hu
  - Andrea C Burrows
  - Mike Borowczak
- title: A blockchain-based carbon credit ecosystem
  authors:
  - Soheil Saraji
  - Mike Borowczak
- title: 'A university''s developmental framework: Creating, implementing, and evaluating
    a K-12 teacher cybersecurity micro-credential course'
  authors:
  - Bekir Mugayitoglu
  - Mike Borowczak
  - Andrea C Burrows
- title: WySLICE - Integrating Computer Science throughout Existing K-12 Core Disciplinary
    Areas
  authors:
  - Mike Borowczak
  - Andrea C Burrows
  - Mason Johnson
- title: Constructing and refining engaging computer science outreach
  authors:
  - Shaya Wolf
  - Rafer Cooley
  - Mason Johnson
  - Andrea C Burrows
  - Mike Borowczak
- title: Building collaboration and securing interest in computer science education
    through outreach opportunities
  authors: 
  - Shaya Wolf
  - Fiona Moss
  - Rasana Manandhar
  - Madison Cooley
  - Rafer Cooley
  - Andrea C Burrows
  - Mike Borowczak
- title: Dynamic Anonymized Evaluation for Behavioral Continuous Authentication
  authors: 
  - Rasana Manandhar
  - Shaya Wolf
  - Mike Borowczak
- title: 'Enabling advanced topics in computing and engineering through authentic
    inquiry: A cybersecurity case study'
  authors:
  - Mike Borowczak
  - Andrea C Burrows
 - title: Hardening freshman engineering student soft skills
  authors:
  - Andrea C Burrows
  - Mike Borowczak
 