# - id: eid:2-s2.0-85138257032
#   authors:
#   - Andey Robins
#   - Andrea C Burrows
#   - Mike Borowczak
#   date: '2022-08-23'

# - id: eid:2-s2.0-85138295410
#   authors:
#   - Shawna Wolf
#   - Shaya Wolf
#   - Hui Hu
#   - Andrea C Burrows
#   - Mike Borowczak
#   date: '2022-08-23'

# - id: eid:2-s2.0-85111015140
#   authors:
#   - Soheil Saraji
#   - Mike Borowczak
#   date: '2021-06-30'

# - id: eid:2-s2.0-85105867054
#   authors:
#   - Bekir Mugayitoglu
#   - Mike Borowczak
#   - Andrea C Burrows
#   date: '2021-03-12'

# - id: lensid:070-581-490-909-767
#   authors:
#   - Mike Borowczak
#   - Andrea C Burrows
#   - Mason Johnson
#   date: '2021-07-26'

# - id: eid:2-s2.0-85095780473
#   authors:
#   - Shaya Wolf
#   - Rafer Cooley
#   - Mason Johnson
#   - Andrea C Burrows
#   - Mike Borowczak
#   date: '2020-06-26'

# - id: eid:2-s2.0-85078773673
#   authors: 
#   - Shaya Wolf
#   - Fiona Moss
#   - Rasana Manandhar
#   - Madison Cooley
#   - Rafer Cooley
#   - Andrea C Burrows
#   - Mike Borowczak
#   date: '2019-06-19'

# - id: eid:2-s2.0-85093401563
#   authors: 
#   - Rasana Manandhar
#   - Shaya Wolf
#   - Mike Borowczak
#   date: '2019-03-19'

# - id: eid:2-s2.0-85051209978
#   authors:
#   - Mike Borowczak
#   - Andrea C Burrows

# - id: eid:2-s2.0-85065661057
#   authors:
#   - Andrea C Burrows
#   - Mike Borowczak
#   date: '2017-08-07'
